server:
  port: 7000

spring:
  application:
    name: member-service

# Eureka
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8088/eureka
    register-with-eureka: true
    fetch-registry: true