server:
  port: 0

spring:
  application:
    name: user-service
#  kafka:
#    consumer:
#      bootstrap-servers: localhost:9092
#      group-id: dev
#      auto-offset-reset: earliest
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

# Eureka
eureka:
  instance:
    hostname: 127.0.0.1
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8088/eureka/
    register-with-eureka: true
    fetch-registry: true