server:
  port: 7000

spring:
  application:
    name: member-service

# Eureka
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8088/eureka/}
    register-with-eureka: true
    fetch-registry: true